name: build-and-push

# on:
#  release:
#    types:
#      - published

on:
  pull_request:
  push:
    branches: [master]

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get latest release version number
      id: get_version
      uses: battila7/get-version-action@v2
    
    
    - name: Some other action
      with:
        destination_dir: ${{ steps.get_version.outputs.version }}
      run: echo ${{ steps.get_version.outputs.version }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::THISTHEREF
      #run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Echo
      run: echo ${{ steps.get_version.outputs.VERSION }}
      shell: bash

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Build and push
    #   id: docker_build
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./
    #     file: ./Dockerfile
    #     push: true
    #     tags: testdockngdev/gha-test:23
        
    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}